language: node_js
node_js:
  - "node"
script: yarn build
cache: yarn

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  script: yarn build
  target-branch: master
  on:
    branch: gh-pages

branches:
  only:
    - gh-pages
